version: 3
pullapprove_conditions:
  - condition: "base.ref == 'master'"
    unmet_status: failure
    explanation: "PullApprove is not configured for this branch"
  - condition: "'[DO NOT REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'[NO REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'No Review' not in labels"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'Do Not Review' not in labels"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "state == 'open'"
    unmet_status: failure
    explanation: "PR must be open to be reviewed"
groups:
  DevOpsGroup:
    conditions:
      - "'dependencies' not in labels"
      - >
        '.circleci/*' in files or
        'bin/*' in files or
        'docker/*' in files or
        'google/*' in files or
        'sandbox/*' in files or
        '.dock*' in files or
        '.env*' in files or
        '.git*' in files
    reviews:
      required: 2
      request: 2
      request_order: shuffle
    reviewers:
      teams:
        - DevOps
