version: 3
pullapprove_conditions:
  - condition: "base.ref == 'master'"
    unmet_status: failure
    explanation: "PullApprove is not configured for this branch"
  - condition: "'[DO NOT REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'[NO REVIEW]' not in title"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'No Review' not in labels"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "'Do Not Review' not in labels"
    unmet_status: pending
    explanation: "Not ready for review"
  - condition: "state == 'open'"
    unmet_status: failure
    explanation: "PR must be open to be reviewed"
groups:
  min_global_approvals:
    conditions:
      - "'dependencies' not in labels"
    labels:
      pending: ❐ Review
      approved: ✓ Review
      rejected: ✘ Review
    reviews:
      required: 3
      request: 3
      request_order: random
    reviewers:
      teams:
        - crumpet-tenured-devs
